import assert from 'node:assert/strict';
import fs from 'node:fs';
const data=JSON.parse(fs.readFileSync('dist/data.json','utf8'));
const elements=new Map();
const el=id=>{if(!elements.has(id))elements.set(id,{value:'',dataset:{},disabled:false,innerHTML:'',textContent:'',events:{},addEventListener(name,handler){this.events[name]=handler;},focus(){}});return elements.get(id);};
el('model').value='5500-2';el('sku').value='116130';el('region').value='US';
const examples=[{model:'5500',sku:'115115'},{model:'5500-2-EU',sku:'116130'}].map(dataset=>({...el('example-'+dataset.model),dataset}));
const downloads=[];const blobs=[];
globalThis.document={getElementById:el,querySelectorAll:()=>examples,createElement:()=>({click(){downloads.push(this.download);}})};
globalThis.fetch=async()=>({ok:true,json:async()=>data});
Object.defineProperty(globalThis,'navigator',{configurable:true,value:{clipboard:{writeText:async text=>{assert(text.includes('US-market'));}}}});
URL.createObjectURL=blob=>{blobs.push(blob);return 'blob:test';};URL.revokeObjectURL=()=>{};
await import('../dist/app.mjs?success');await new Promise(setImmediate);
assert.equal(el('result').dataset.status,'documented');assert(el('reply').textContent.includes('US-market'));
el('model').value='5500';await el('form').events.submit({preventDefault(){}});assert.equal(el('result').dataset.status,'unknown');
await examples[0].events.click();assert.equal(el('result').dataset.status,'documented');assert.equal(el('sku').value,'115115');
await examples[1].events.click();assert.equal(el('result').dataset.status,'unknown');assert(el('reply').textContent.includes('not verified'));
el('model').value='5500-2';el('region').value='other';await el('form').events.submit({preventDefault(){}});assert.equal(el('result').dataset.status,'unknown');
el('region').value='US';await el('copy').events.click();assert.equal(el('notice').textContent,'Reply copied.');
navigator.clipboard.writeText=async()=>{throw Error('denied');};await el('copy').events.click();assert(el('notice').textContent.includes('Copy unavailable'));assert(el('reply').textContent.includes('US-market'));
await el('download').events.click();assert.equal(downloads.at(-1),'fit-before-buy-audit.json');const audit=JSON.parse(await blobs.at(-1).text());assert.equal(audit.status,'documented');assert.equal(audit.sources.length,2);assert.equal(audit.schemaVersion,2);
await el('export').events.click();assert.equal(downloads.at(-1),'fit-before-buy-source-register.json');assert.equal(JSON.parse(await blobs.at(-1).text()).sources.length,5);
await el('run').events.click();assert(el('checks').innerHTML.includes('30/30'));
globalThis.fetch=async()=>({ok:false});await import('../dist/app.mjs?failure');await new Promise(setImmediate);assert.equal(el('result').dataset.status,'unknown');for(const id of ['download','copy','run','export'])assert.equal(el(id).disabled,true);assert(el('reply').textContent.includes('No reply'));
console.log('10 application flow contracts passed: initialization, submit, examples, region, copy success/failure, audit/register exports, checks, evidence-load failure. Simulated DOM; no browser visual QA.');
